#if !canImport(ObjectiveC)
import XCTest

extension ISBNTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ISBNTests = [
        ("testConversion", testConversion),
        ("testIsISBN10", testIsISBN10),
        ("testIsISBN13", testIsISBN13),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ISBNTests.__allTests__ISBNTests),
    ]
}
#endif
